version: '3.8'
services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: crawler
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    networks:
      - network

volumes:
  mongo-data:
    driver: local
  mongo-config:
    driver: local

networks:
  network:
    name: crawler
    driver: bridge